### ISSUE TITLE
Issue when installing to a fresh Raspberry Pi

### ISSUE THREAD

**Issue by huseyinkogo** [mishop/sensors#1]
Experiencing an issue when installing, I'm new into stuff, help will be very appreciated.

Could give me a hand on getting this running, please preview the attachment 

![image_2022-01-10_115010](https://user-images.githubusercontent.com/76049382/148708116-f9e53b0a-a15e-4373-b5bc-de6ad634f624.png)

**Comment by mishop** [comment]
I will update today. This is old file need go.mod file for using.

**Comment by mishop** [comment]
Updated, now working without lib. 
After install if not run sensors, copy file form $GOPATH/bn to /usr/bin
`sudo cp ~/go/bin/sensors /usr/bin/`
